org: shehanp12
app: backend
service: libraryManagmentSystem
# Create an optimized package for our functions
package:
  individually: true
plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
 
  environment:
    tableName: ${env:tableName}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}
   
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:AmazonDynamoDBFullAccess
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
functions:
  
  create:
    handler: create.main
    events:
      - http:
          path: libraryManagement
          method: post
          cors:
            origin:
              Access-Control-Allow-Origin: '*'
              Access-Control-Allow-Credentials: true
            allowCredentials: false
          authorizer:
            arn: arn:aws:cognito-idp:ap-south-1:323270932585:userpool/ap-south-1_NmptlLWJM

  createUser:
    handler: createUser.main
    events:
      - http:
          path: libraryManagement/user
          method: post
          cors: true
           
          authorizer:
            arn: arn:aws:cognito-idp:ap-south-1:323270932585:userpool/ap-south-1_NmptlLWJM
   
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: libraryManagement/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: libraryManagement
          method: get
          cors: true
          authorizer: aws_iam

  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: libraryManagement/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /notes/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: libraryManagement/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  billing:
    # Defines an HTTP API endpoint that calls the main function in billing.js
    # - path: url path is /billing
    # - method: POST request
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
