import { v4 as uuid } from "uuid";
import user01 from "../static/images/users/23.jpeg";
import user02 from "../static/images/users/22.jpeg";
import user03 from "../static/images/users/24.jpeg";

export default [
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "WESTERN PROVINCE",
      city: "COLOMBO",
      street: "NO.78/118 NALANDA Street",
    },
    avatarUrl: user01,
    createdAt: 1555016400000,
    email: "SAMANTH.KUMARA@gmail.com",
    name: "SAMANTHA KUNARA",
    phone: "0775672345",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "NORTHERN",
      city: "JAFFNA",
      street: "1865 Suva Road",
    },
    avatarUrl: user02,
    createdAt: 1555016400000,
    email: "ramanndan2000@gmail.com",
    name: "Ramanndan Kumara",
    phone: "0775567345",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Northwestern province",
      city: "Puttalama",
      street: "No.12/234, Adiambalama",
    },
    avatarUrl: user03,
    createdAt: 1555016400000,
    email: "nirmal33@gmail.com",
    name: "Nirmal Jayasingha",
    phone: "0756723143",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Eastern",
      city: "Ampara",
      street: "No12, Main road",
    },
    avatarUrl: "/static/images/avatars/avatar_5.png",
    createdAt: 1554930000000,
    email: "anjupp@gmsil.com",
    name: "Anjula Perera",
    phone: "0712343456",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Uva",
      city: "Badulla",
      street: "No 3, University Road",
    },
    avatarUrl: "/static/images/avatars/avatar_6.png",
    createdAt: 1554757200000,
    email: "kumarinu@gmail.com",
    name: "Kumari Nuwanthika",
    phone: "076342443",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Western",
      city: "Gampaha",
      street: "No317, Angus Road",
    },
    avatarUrl: "/static/images/avatars/avatar_1.png",
    createdAt: 1554670800000,
    email: "rovindunenuk21@gmail.com",
    name: "Rovinu Nenuka",
    phone: "0743323457",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Western",
      city: "Negombo",
      street: "No 01, St.Peters road",
    },
    avatarUrl: "/static/images/avatars/avatar_7.png",
    createdAt: 1554325200000,
    email: "perera001@gmail.com",
    name: "Jhosph Perera",
    phone: "0778967008",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Central",
      city: "Kandy",
      street: "17/123, High Road",
    },
    avatarUrl: "/static/images/avatars/avatar_8.png",
    createdAt: 1523048400000,
    email: "wasanthiamanda234@gmail.com",
    name: "Amanda Wasanthi",
    phone: "0771234345",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "Southern",
      city: "Gall",
      street: "No 12, Gall road",
    },
    avatarUrl: "/static/images/avatars/avatar_9.png",
    createdAt: 1554702800000,
    email: "kumaragall345@gmial.com",
    name: "Wasantha Kuamra",
    phone: "0754563409",
  },
  {
    id: uuid(),
    address: {
      country: "SRI LANKA",
      state: "North Central",
      city: "Anuradhapura",
      street: "No 134, Tempal road",
    },
    avatarUrl: "/static/images/avatars/avatar_10.png",
    createdAt: 1522702800000,
    email: "boo123@gmail.com",
    name: "Boopathy Nirmal",
    phone: "0775643209",
  },
];
